### ISSUE TITLE
Update to vaultwarden 1.32

### ISSUE THREAD

**Issue by jdeath** [hassio-addons/addon-bitwarden#317] opened 2024-09-07 10:46 UTC
# Problem/Motivation

Vautlwarden was updated 1.32.0 weeks ago to fix many CVE's. The `renovate[bot]` for this addon updated the code on Aug 12, but a new release has not been made as of Sep 7. 

Without a release, users cannot upgrade easily. One could clone and update the release themselves, but since information is stored in /data inside the container, it is difficult to port 

## Expected behavior

A new release is made

## Actual behavior

No release is made

## Steps to reproduce

Update addon-store

## Proposed changes

Make a new release 0.23

**Comment by tjorim** [comment] 2024-09-07 12:28
Duplicate of #314.

**Closed by tjorim** 2024-09-07 12:28 UTC

**Comment by jdeath** [comment] 2024-09-08 11:32
Not sure why #314 was closed, since not completed. If HA is no longer supporting vaultwarden, both myself (https://github.com/jdeath/homeassistant-addons) and Alex Belgium (https://github.com/alexbelgium/hassio-addons) have a version that auto-updates. There are instructions in my version on how to move your configuration over. My version is different because it stores the information outside the container in addon_configs/,  which is still secure if you use an argon admin password. It also does not edit the official container.
