### ISSUE TITLE
Add optional environment

### ISSUE THREAD

**Issue by niekniek89** [hassio-addons/addon-bitwarden#95] opened 2021-03-10 12:24 UTC
Hi,

it is possible to specify these variables:

SIGNUPS_ALLOWED	**false**

I have bitwarden open to the outside.
but now anyone can create bitwarden vaults.

this is no longer possible with these variables.
no idea if this is possible.

**Comment by sinclairpaul** [comment] 2021-03-10 15:20
Duplicate of #36 

Use the admin panel

**Closed by sinclairpaul** 2021-03-10 15:20 UTC

**Comment by niekniek89** [comment] 2021-03-10 18:50
thank you very much. it worked.
