### ISSUE TITLE
Cant update Bitwarden

### ISSUE THREAD

**Issue by AJEvans3** [hassio-addons/addon-bitwarden#47] opened 2020-10-27 04:43 UTC
# Problem/Motivation

> inavlid master password error

## Expected behavior

> i can login successfully to my self hosted bitwarden vault - but when i lock the application and try to unlock it again the following message is prompted:

"An error has occurred - invalid master password"

## Actual behavior

> I believe its because my server needs to be updated to 1.63. Its currently 1.14

**Comment by damanti-me** [comment] 2020-10-27 06:24
#35

**Comment by mironalessandro** [comment] 2020-10-27 17:06
@damanti-me nobody check this issues I think... Maybe is better if we don't use this addon

**Comment by damanti-me** [comment] 2020-10-27 17:25
Yeah sadly it's kind of deprecated...

**Comment by frenck** [comment] 2020-10-27 20:04
Closing as a duplicate of #35

**Closed by frenck** 2020-10-27 20:04 UTC

**Comment by rutgerkra** [comment] 2020-10-30 14:41
@frenck If as you say the addon is still maintained, please do so. I don't mean stop everything you're doing and update it asap, but you could also engage with the issue and share some time frame in which you expect to be able to handle it. If that's not possible, that's also information that people would appreciate. Any response would be welcome at this point, since atm the only people engaging with #35 are users that are facing the issue and the last update on the repo was on July 22. I don't think it is surprising that people think the addon is not actively maintained if you take these points into consideration.

**Comment by frenck** [comment] 2020-10-30 14:47
Thanks for the feedback @rutgerkra I don't work on a schedule, so anything I would say on that isn't fair to anyone. Hence I don't.
