### ISSUE TITLE
Unlock in APP doest not work, have to log out and login again

### ISSUE THREAD

**Issue by xppx99** [hassio-addons/addon-bitwarden#35] opened 2020-08-06 09:14 UTC
# Problem/Motivation

When trying to unlock the vault using the APP in linux (tested ubuntu and mint), it fails saying invalid master password. Unlocking using firefox extension works. The workaround is log off and then login again

## Proposed changes

This is a known bug, and is already fixed with https://github.com/dani-garcia/bitwarden_rs/issues/1084

Can you please push this fix to the addon? 

Thanks in advance. 

Regards

**Comment by steve-gombos** [comment] 2020-08-23 23:28
Can also say that this is an issue on the windows desktop app as well.

**Comment by daranto** [comment] 2020-09-11 07:12
I have the same problem. Its super annoying :(

An Update to the newest version would be wonderful.

**Comment by Razer0123** [comment] 2020-09-17 21:07
Having the same issue after a fresh Windows wipe

This addon seems dead, no support at all

**Comment by fozoglu** [comment] 2020-09-18 14:41
I have the same problem. Available in both Windows and Mac apps. Same problem with Safari and Chrome extension. It works stably only on the iPhone application.

**Comment by daranto** [comment] 2020-09-18 17:16
For now I have the workaround. You can set the program to log out after restarting. With this you avoid the one click. But this is not a nice solution - because the problem is already fixed. So it would be great if the addon is simply upgraded to the latest version.

**Comment by Xerionty** [comment] 2020-09-21 22:11
Can confirm that the issue still persists. https://community.bitwarden.com/t/cant-unlock-desktop-client-with-master-password-after-1-20/13728

**Comment by xppx99** [comment] 2020-09-29 23:24
Unfortunately I was no longer able to wait for the update as I consider my passwords access important. This is not a major bug but the situation states clearly that the addon is not so much supported by anyone besides Frank, who must be really busy with other things...

For this reason I decided to host Bitwarden_RS myself.

**Comment by damanti-me** [comment] 2020-09-30 06:08
In my option it's really unnecessary to inform everybody about that fact. Cheers.

**Comment by magicbret** [comment] 2020-10-09 13:21
Hi there, issue still there. It's also the case for the Fedora 32 desktop app and web browser extensions. Waiting for the solution. Thanks

**Comment by rutgerkra** [comment] 2020-10-12 23:12
This issue has been fixed since bitwarden_rs version 1.16.2, which came out on August 6. I see that @fozoglu's attempt to update the dockerfile was not thorough enough to be incorporated, but @frenck did not give specifics on what was necessary to upgrade, just that the edit was not compatible cross-architecture. It's too bad I don't know enough about this to help out, but some info on the matter would be nice. I must say that waiting for three layers of updates to catch up until they finally reach you is starting to feel like a bad idea. No offense to @frenck of course, it is clear he's working on countless things at the same time. It's just an unfortunate situation to rely on a single developer for maintaining an application that is quite vital to its users.

**Comment by viperdream26** [comment] 2020-10-22 17:16
Been having the same issue for a little while in the Chrome Extension.

Bitwarden RS 1.17 is now released: https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.17.0

Here's hoping that we can have the HassIO Add-On upgraded soon. Thank you Frenck and all devs for your hard work! I've given several friends and family members little "seminars" on Bitwarden (with overall and HA context). It's really just outstanding!

**Comment by reharmsen** [comment] 2020-10-31 09:09
I'm having same issue with the Edge Extension.
Would be nice when the addon can at least be updated to 1.16.2 in the near future

**Comment by mattbruman** [comment] 2020-11-02 20:49
Didn't have the issue until about 3 days ago, its weird that it happens so late after using the server since I have been using it for 3 months. It doesn't do it on the android app just on the desktop with extensions. When will this fix get pushed? For something that needs to secure peoples passwords I would think getting this updated should be a priority. Please reopen

**Comment by rutgerkra** [comment] 2020-11-05 12:54
Well, I switched over to Bitwarden premium. At the end of the day we're talking about a password manager that is housing much too important information for the current update "cycle".

**Comment by frso80** [comment] 2020-11-11 12:46
I've installed this today and having the same issue both in the macOS client and Chrome plug-in.

**Comment by circa1665** [comment] 2020-11-27 10:24
Having the same issue, have had no problems with Bitwarden until now.

**Comment by JOHLC** [comment] 2020-12-09 18:06
Same issues here with all clients

**Comment by Nailik** [comment] 2020-12-16 10:11
This issues is known at bitwarden 
@https://github.com/bitwarden/mobile/issues/1125 
They didn't care about it yet

**Comment by Nailik** [comment] 2020-12-16 10:15
@frenck can you please look into this. We really need an update on the plugin ...

**Comment by assices** [comment] 2020-12-21 09:14
Hello,

I installed latest Bitwarden_rs version as docker container on my Home Assistant (Rasp 4 + Hassio).
This a temporary workaround for me, waiting for a structured resolution (official addon upgrade).
I am aware that it is not the most reliable and recommended solution, but I am Bitwarden addicted and using it with the issue was quite frustrating.

**Comment by lbouriez** [comment] 2021-01-19 01:21
> Hello,
> 
> I installed latest Bitwarden_rs version as docker container on my Home Assistant (Rasp 4 + Hassio).
> This a temporary workaround for me, waiting for a structured resolution (official addon upgrade).
> I am aware that it is not the most reliable and recommended solution, but I am Bitwarden addicted and using it with the issue was quite frustrating.

You create an addon ? If yes can you share the config.json ?

**Comment by assices** [comment] 2021-01-20 08:29
> > Hello,
> > I installed latest Bitwarden_rs version as docker container on my Home Assistant (Rasp 4 + Hassio).
> > This a temporary workaround for me, waiting for a structured resolution (official addon upgrade).
> > I am aware that it is not the most reliable and recommended solution, but I am Bitwarden addicted and using it with the issue was quite frustrating.
> 
> You create an addon ? If yes can you share the config.json ?

ciao Laurent,

No, I preferred to install it as container. 
With a little familiarity with Docker, it's a quite easy work (data migration from Bitwarden add-on also). 
In order to simplify data backup, I mapped container data to an Hassio local folder ("snaphoted") with a bind. 

If you are looking for an updated addon, I suggest you to evaluate forks. I saw someone updated Bitwarden image.

**Comment by frenck** [comment] 2021-01-20 13:25
This is fixed in v0.7.0 of the add-on.

<https://github.com/hassio-addons/addon-bitwarden/releases/tag/v0.7.0>

**Closed by frenck** 2021-01-20 13:25 UTC
