### ISSUE TITLE
Cannot delete items from Desktop app

### ISSUE THREAD

**Issue by Razer0123** [hassio-addons/addon-bitwarden#31] opened 2020-06-16 15:35 UTC
# Problem/Motivation

Cannot delete items from Mac Desktop app

## Expected behavior

Being able to delete the item

## Actual behavior

Can't delete, only works via browser

`(Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko))
[2020-06-16 17:36:47][request][INFO] PUT /api/ciphers/XXXXXXXXXX/delete
[2020-06-16 17:36:47][response][INFO] 404 Not Found
[16/Jun/2020:17:36:47 +0200] 404 -(192.168.1.1) PUT /api/ciphers/XXXXXXXXXXX/delete HTTP/1.1 `

## Steps to reproduce

Open the Desktop app, login, try to delete an item

## Proposed changes

A fix? Not sure if there is any way I could help debugging this

**Comment by Razer0123** [comment] 2020-06-16 15:41
From what I can see updating to latest Bitwarden RS should fix the issue

**Comment by Razer0123** [comment] 2020-06-16 15:45
This is the same issue on Bitwarden RS repo, should give an idea on how to fix it

https://github.com/dani-garcia/bitwarden_rs/issues/1021

**Comment by DasLetzteEinhorn** [comment] 2020-07-01 15:29
The Problem could be the old image version that is used in the current addon version (0.6.2).

**Comment by Razer0123** [comment] 2020-07-19 20:26
So what do i have to do?

**Comment by DasLetzteEinhorn** [comment] 2020-07-19 21:33
I'd say we have to wait for the Addon being updated. Or you could install Bitwarden_rs as a standalone docker container, depending on your installation method.

**Comment by houseofbugs** [comment] 2020-07-30 23:22
I am having this same issue now. Is this addon abandoned? :(

**Comment by frenck** [comment] 2020-07-31 10:47
No it is not abandoned, check the latest commits and you'll see recent changes have been made. There is an issue caused by upstream issues for which a solution needs to be found.

**Comment by houseofbugs** [comment] 2020-08-01 08:58
What issue is that? I see the commits but they are just version number changes.

**Comment by houseofbugs** [comment] 2020-08-01 09:04
Whats the issue thats preventing it? Anything I can help with?

**Comment by colinfrei** [comment] 2020-08-11 13:32
I have the feeling a new version needs to be tagged that contains the latest commits from July. The latest tag references an older version of bitwarden_rs.

I'm not sure if this is related to the latest builds failing? https://gitlab.com/hassio-addons/addon-bitwarden/pipelines

**Comment by Razer0123** [comment] 2020-08-29 12:43
Can we expect an update anytime soon?

I am also missing the trash feature

**Comment by houseofbugs** [comment] 2020-08-30 05:15
I tried doing my own and gave up. I just moved over to lastpass instead.  :/

**Comment by Simperdy** [comment] 2020-12-14 15:28
Can confirm that you cant delete entry from the IOS or Android App. Installed the newer version of the bitwarden rs server (Version 1.17.0) as docker container and there it works.

**Comment by DasLetzteEinhorn** [comment] 2021-01-20 03:48
> There hasn't been any activity on this issue recently, so we clean up some of the older and inactive issues.
> Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by leaving a comment 👍
> This issue has now been marked as stale and will be closed if no further activity occurs. Thanks!

Issue is still not resolved.

**Comment by ThePirat91** [comment] 2021-01-20 07:15
I totally agree with @DasLetzteEinhorn.
The issue is still definitively there.

**Comment by frenck** [comment] 2021-01-20 13:24
This should be fixed with v0.7.0:

<https://github.com/hassio-addons/addon-bitwarden/releases/tag/v0.7.0>

Could you test this?

**Comment by DasLetzteEinhorn** [comment] 2021-01-20 14:02
> This should be fixed with v0.7.0:
> 
> https://github.com/hassio-addons/addon-bitwarden/releases/tag/v0.7.0
> 
> Could you test this?

This issue is now resolved. Thank you very much!

**Comment by frenck** [comment] 2021-01-20 14:03
Awesome! Thanks for letting me know 👍

**Closed by frenck** 2021-01-20 14:03 UTC

**Comment by ThePirat91** [comment] 2021-01-21 07:07
> 
> 
> Awesome! Thanks for letting me know 👍

Thanks a lot frenck. I can confirm too that It's working like a charm now. ;)
