### ISSUE TITLE
Server timezone is on UTC so TOTP codes are not working

### ISSUE THREAD

**Issue by guerrerotook** [hassio-addons/addon-bitwarden#141] opened 2021-06-16 07:53 UTC
# Problem/Motivation

I can't login to my Bitwarden Vault because all the TOTP codes fails because the server timezone is configured in UTC but my home assistant and myself are CEST time zone. 

root@a0d7b954-bitwarden:/# dpkg-reconfigure tzdata

Current default time zone: 'Etc/UTC'
Local time is now:      Wed Jun 16 07:48:08 UTC 2021.
Universal Time is now:  Wed Jun 16 07:48:08 UTC 2021.

## Expected behavior

For the TOTP codes to work and be able to login.

## Actual behavior

This is what the web UI says:

Invalid TOTP code! Server time: 2021-06-16 07:44:16 UTC.

## Steps to reproduce

I don't really know to reproduce this, but having the container for the bitwarden on UTC and your current time zone in any other.

**Comment by Eeems** [comment] 2021-07-13 15:56
Possibly a duplicate of #12?

**Comment by frenck** [comment] 2021-08-21 21:06
This is probably caused by this add-on running as a service. This needs to be adjusted to application level.

**Closed** 2021-08-21 21:11 UTC
