### ISSUE TITLE
Update to 1.38.4 to solve some big problems with iOS App

### ISSUE THREAD

**Issue by poudenes** [hassio-addons/addon-bitwarden#58] opened 2021-01-14 09:35 UTC
Have probems with latest iOS and Self hosting Bitwarden:

**_(Saw this on the community site of Bitwarden)_**
Hi There! First of all love the app and being able to host my own server!

So recently (I don’t know how recent) I’ve been having issues with my iPhone Bitwarden App.

I cannot just unlock the app with my master password. It says “Invalid Master Password. Try Again”. Basically I have to fully logout of the app and then re-login in order to access my passwords. I have confirmed I’m using the correct login and password. Also the option with the integration in the keyboard to access bitwarden will not work. It has the same message when I try to access my vault from the keyboard.

I have tried deleting/logging out then in, and restarted my phone but still it has the same behavior.

Anyone experience this? And if so, have they been able to resolve it?

Thanks!

**_Answer:_**
Make sure your server is running the latest version (1.38.4) as there are new pieces of information in the API that the client apps need to unlock correctly.

**Comment by frenck** [comment] 2021-01-14 11:07
Duplicate of other issues, please check the open issue before opening a new one. Thanks 👍

**Closed by frenck** 2021-01-14 11:07 UTC

**Comment by poudenes** [comment] 2021-01-14 11:09
I did, but there was nothing that look like this
